// <auto-generated />
using System;
using AnimalShelterApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnimalShelterApi.Migrations
{
    [DbContext(typeof(AnimalShelterApiContext))]
    [Migration("20230211040907_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnimalShelterApi.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Age = 5,
                            DateAdded = new DateTime(2023, 2, 10, 20, 9, 7, 226, DateTimeKind.Local).AddTicks(7970),
                            Description = "Black and white cat",
                            Name = "Izze",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 2,
                            Age = 12,
                            DateAdded = new DateTime(2023, 2, 10, 20, 9, 7, 226, DateTimeKind.Local).AddTicks(8020),
                            Description = "Small dog with black, brown, and orange fur.",
                            Name = "Kobe",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 3,
                            Age = 10,
                            DateAdded = new DateTime(2023, 2, 10, 20, 9, 7, 226, DateTimeKind.Local).AddTicks(8020),
                            Description = "Medium dog with black, brown,orange, and white fur.",
                            Name = "Shadow",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 4,
                            Age = 14,
                            DateAdded = new DateTime(2023, 2, 10, 20, 9, 7, 226, DateTimeKind.Local).AddTicks(8020),
                            Description = "Small black and white dog.",
                            Name = "AJ",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 5,
                            Age = 10,
                            DateAdded = new DateTime(2023, 2, 10, 20, 9, 7, 226, DateTimeKind.Local).AddTicks(8030),
                            Description = "Grey tabbey.",
                            Name = "Bella",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 6,
                            Age = 8,
                            DateAdded = new DateTime(2023, 2, 10, 20, 9, 7, 226, DateTimeKind.Local).AddTicks(8030),
                            Description = "Ginger and white cat.",
                            Name = "Ziggy",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 7,
                            Age = 6,
                            DateAdded = new DateTime(2023, 2, 10, 20, 9, 7, 226, DateTimeKind.Local).AddTicks(8030),
                            Description = "Grey with black stripes.",
                            Name = "Marley",
                            Species = "Cat"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
